### ISSUE TITLE
peewee.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test_peewee`.`node`, CONSTRAINT `node_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `node` (`id`))')   

### ISSUE THREAD

**Issue by slukin1** [mathieurodic/peewee-tree#1]
peewee.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test_peewee_tree`.`node`, CONSTRAINT `node_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `node` (`id`))')
db = MySQLDatabase

**Comment by mathieurodic** [comment]
I changed:

``` python
parent = ForeignKeyField('self', default=0)
```

to:

``` python
parent = ForeignKeyField('self', default=None, null=True)
```

Does it solve the problem?

**Comment by slukin1** [comment]
With parent = ForeignKeyField('self', default=None, null=True) works well if peewee version 2.2.4
but with peewee version 2.6.4 error:
    row = self.select().where(self.pk_expr()).first()
AttributeError: 'Node' object has no attribute 'pk_expr'

**Comment by slukin1** [comment]
With peewee version 2.6.4 all ok if self.pk_expr() changed to self._pk_expr() in row = self.select().where(self._pk_expr()).first()

**Comment by mathieurodic** [comment]
Thank you! It's been corrected.
